# Generated by Django 5.2.7 on 2025-10-28 12:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleLibro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resumen', models.TextField(blank=True, null=True, verbose_name='Resumen')),
                ('num_paginas', models.PositiveIntegerField(default=0, verbose_name='Número de páginas')),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, db_index=True, default='', max_length=255, verbose_name='Título')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('isbn', models.CharField(max_length=13, unique=True, verbose_name='ISBN')),
                ('publicado', models.DateField(blank=True, null=True, verbose_name='Fecha de publicación')),
                ('_precio', models.DecimalField(db_column='precio', decimal_places=2, max_digits=8, verbose_name='Precio (€)')),
                ('_stock', models.PositiveIntegerField(db_column='stock', default=0, verbose_name='Stock')),
            ],
            options={
                'ordering': ['titulo'],
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='autor',
            options={'ordering': ['apellido', 'nombre'], 'verbose_name': 'Autor', 'verbose_name_plural': 'Autores'},
        ),
        migrations.AlterModelOptions(
            name='genero',
            options={'ordering': ['nombre'], 'verbose_name': 'Género', 'verbose_name_plural': 'Géneros'},
        ),
        migrations.AddField(
            model_name='autor',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Fecha de creación'),
        ),
        migrations.AddField(
            model_name='autor',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación'),
        ),
        migrations.AddField(
            model_name='autor',
            name='titulo',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255, verbose_name='Título'),
        ),
        migrations.AddField(
            model_name='genero',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Fecha de creación'),
        ),
        migrations.AddField(
            model_name='genero',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación'),
        ),
        migrations.AddField(
            model_name='genero',
            name='titulo',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='autor',
            name='apellido',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='autor',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='autor',
            name='nacionalidad',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nacionalidad'),
        ),
        migrations.AlterField(
            model_name='autor',
            name='nombre',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='genero',
            name='nombre',
            field=models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Nombre'),
        ),
        migrations.AddConstraint(
            model_name='autor',
            constraint=models.UniqueConstraint(fields=('nombre', 'apellido', 'fecha_nacimiento'), name='uq_autor_nombre_apellido_fnac'),
        ),
        migrations.AddField(
            model_name='libro',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='libros', to='books.autor', verbose_name='Autor'),
        ),
        migrations.AddField(
            model_name='libro',
            name='generos',
            field=models.ManyToManyField(related_name='libros', to='books.genero', verbose_name='Géneros'),
        ),
        migrations.AddField(
            model_name='detallelibro',
            name='libro',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detalle', to='books.libro'),
        ),
    ]
