# Generated by Django 5.2.7 on 2025-10-28 12:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, db_index=True, default='', max_length=255, verbose_name='Título')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('nombre', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Género',
                'verbose_name_plural': 'Géneros',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, db_index=True, default='', max_length=255, verbose_name='Título')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('nombre', models.CharField(db_index=True, max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(db_index=True, max_length=100, verbose_name='Apellido')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('nacionalidad', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nacionalidad')),
                ('sitio_web', models.URLField(blank=True, null=True, verbose_name='Sitio web')),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autores',
                'ordering': ['apellido', 'nombre'],
                'constraints': [models.UniqueConstraint(fields=('nombre', 'apellido', 'fecha_nacimiento'), name='uq_autor_nombre_apellido_fnac')],
            },
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, db_index=True, default='', max_length=255, verbose_name='Título')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('isbn', models.CharField(max_length=13, unique=True, verbose_name='ISBN')),
                ('publicado', models.DateField(blank=True, null=True, verbose_name='Fecha de publicación')),
                ('_precio', models.DecimalField(db_column='precio', decimal_places=2, max_digits=8, verbose_name='Precio (€)')),
                ('_stock', models.PositiveIntegerField(db_column='stock', default=0, verbose_name='Stock')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='libros', to='libros.autor', verbose_name='Autor')),
                ('generos', models.ManyToManyField(related_name='libros', to='libros.genero', verbose_name='Géneros')),
            ],
            options={
                'ordering': ['titulo'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DetalleLibro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resumen', models.TextField(blank=True, null=True, verbose_name='Resumen')),
                ('num_paginas', models.PositiveIntegerField(default=0, verbose_name='Número de páginas')),
                ('libro', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detalle', to='libros.libro')),
            ],
        ),
    ]
